// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import type * as WhatsappSDK from "../../../index.js";

export declare namespace MediaClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MediaClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MediaClient.Options>;

    constructor(options: MediaClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieve media metadata (URL, mime type, size) by media ID.
     *
     * @param {string} mediaId
     * @param {WhatsappSDK.WhatsappApiGetMediaRequest} request
     * @param {MediaClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.media.getMedia("mediaId")
     */
    public getMedia(
        mediaId: string,
        request: WhatsappSDK.WhatsappApiGetMediaRequest = {},
        requestOptions?: MediaClient.RequestOptions,
    ): core.HttpResponsePromise<WhatsappSDK.WhatsappApiRetrieveMediaResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getMedia(mediaId, request, requestOptions));
    }

    private async __getMedia(
        mediaId: string,
        request: WhatsappSDK.WhatsappApiGetMediaRequest = {},
        requestOptions?: MediaClient.RequestOptions,
    ): Promise<core.WithRawResponse<WhatsappSDK.WhatsappApiRetrieveMediaResponse>> {
        const { phone_number_id: phoneNumberId } = request;
        const _queryParams: Record<string, unknown> = {
            phone_number_id: phoneNumberId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.WhatsappSDKEnvironment.Production
                    ).graph,
                `${core.url.encodePathParam(mediaId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as WhatsappSDK.WhatsappApiRetrieveMediaResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.WhatsappSDKError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/{mediaId}");
    }
}
