// This file was auto-generated by Fern from our API Definition.

export interface WhatsappApiRetrieveMediaResponse {
    messaging_product: "whatsapp";
    url: string;
    mime_type: string;
    sha256: string;
    file_size: number;
    id: string;
}
