// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface ErrorObject {
    code: number;
    title: string;
    message: string;
    error_data: WhatsappSDK.ErrorData;
}
