// This file was auto-generated by Fern from our API Definition.

/** ISO 3166-1 alpha-2 country codes supported by WhatsApp data localisation. */
export const IsoCountryCode = {
    Au: "AU",
    Id: "ID",
    In: "IN",
    Jp: "JP",
    Sg: "SG",
    Kr: "KR",
    De: "DE",
    Ch: "CH",
    Gb: "GB",
    Br: "BR",
    Bh: "BH",
    Za: "ZA",
    Ae: "AE",
    Ca: "CA",
} as const;
export type IsoCountryCode = (typeof IsoCountryCode)[keyof typeof IsoCountryCode];
