// This file was auto-generated by Fern from our API Definition.

export interface ContactOrg {
    company?: string | undefined;
    department?: string | undefined;
    title?: string | undefined;
}
