// This file was auto-generated by Fern from our API Definition.

export interface ContactAddress {
    street?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    zip?: string | undefined;
    country?: string | undefined;
    country_code?: string | undefined;
    type?: string | undefined;
}
