// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface Contact {
    name: WhatsappSDK.ContactName;
    phones: WhatsappSDK.ContactPhone[];
    addresses?: WhatsappSDK.ContactAddress[] | undefined;
    emails?: WhatsappSDK.ContactEmail[] | undefined;
    urls?: WhatsappSDK.ContactUrl[] | undefined;
    org?: WhatsappSDK.ContactOrg | undefined;
    birthday?: string | undefined;
}
