// This file was auto-generated by Fern from our API Definition.

export const FlowMode = {
    Draft: "draft",
    Published: "published",
} as const;
export type FlowMode = (typeof FlowMode)[keyof typeof FlowMode];
