// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface InteractiveAction {
    name?: string | undefined;
    parameters?: WhatsappSDK.InteractiveFlowParameters | undefined;
    button?: string | undefined;
    buttons?: WhatsappSDK.InteractiveActionButtonReply[] | undefined;
    catalog_id?: string | undefined;
    product_retailer_id?: string | undefined;
    sections?: WhatsappSDK.InteractiveSection[] | undefined;
    mode?: WhatsappSDK.FlowMode | undefined;
}
