// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface InteractiveFlowParameters {
    flow_message_version?: string | undefined;
    flow_token?: string | undefined;
    flow_name?: string | undefined;
    flow_cta?: string | undefined;
    flow_action?: WhatsappSDK.InteractiveFlowAction | undefined;
    flow_action_payload?: WhatsappSDK.FlowActionPayload | undefined;
    mode: WhatsappSDK.FlowMode;
}
