// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface InteractiveSection {
    title: string;
    rows: WhatsappSDK.InteractiveSectionRow[];
    product_items?: WhatsappSDK.InteractiveProductItem[] | undefined;
}
