// This file was auto-generated by Fern from our API Definition.

export const InteractiveActionType = {
    Button: "button",
    CatalogMessage: "catalog_message",
    List: "list",
    Product: "product",
    ProductList: "product_list",
    Flow: "flow",
} as const;
export type InteractiveActionType = (typeof InteractiveActionType)[keyof typeof InteractiveActionType];
