// This file was auto-generated by Fern from our API Definition.

export const InteractiveFlowAction = {
    Navigate: "navigate",
    DataExchange: "data_exchange",
} as const;
export type InteractiveFlowAction = (typeof InteractiveFlowAction)[keyof typeof InteractiveFlowAction];
