// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface InteractiveVideoHeader {
    type: "video";
    video: WhatsappSDK.VideoByLink;
}
