// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export type InteractiveHeader =
    | WhatsappSDK.InteractiveTextHeader
    | WhatsappSDK.InteractiveVideoHeader
    | WhatsappSDK.InteractiveDocumentHeader
    | WhatsappSDK.InteractiveImageHeader;
