// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface SendMessageResponse {
    messaging_product: "whatsapp";
    contacts: WhatsappSDK.SendMessageContactResult[];
    messages: WhatsappSDK.SendMessageMessageResult[];
}
