// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface SendMessageRequest {
    messaging_product: "whatsapp";
    to: string;
    type: WhatsappSDK.MessageType;
    preview_url?: boolean | undefined;
    recipient_type?: string | undefined;
    biz_opaque_callback_data?: string | undefined;
    context?: WhatsappSDK.SendMessageContext | undefined;
    text?: WhatsappSDK.TextMessage | undefined;
    reaction?: WhatsappSDK.ReactionMessage | undefined;
    location?: WhatsappSDK.LocationMessage | undefined;
    audio?: WhatsappSDK.AudioMessage | undefined;
    document?: WhatsappSDK.DocumentMessage | undefined;
    image?: WhatsappSDK.ImageMessage | undefined;
    video?: WhatsappSDK.VideoMessage | undefined;
    sticker?: WhatsappSDK.StickerMessage | undefined;
    interactive?: WhatsappSDK.InteractiveMessage | undefined;
    template?: WhatsappSDK.TemplateMessage | undefined;
    contacts?: WhatsappSDK.ContactMessage | undefined;
}
