// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface ShowTypingIndicatorRequest {
    messaging_product: "whatsapp";
    status: "read";
    message_id: string;
    typing_indicator: WhatsappSDK.TypingIndicator;
}
