// This file was auto-generated by Fern from our API Definition.

export const TemplateParameterType = {
    Text: "text",
    Currency: "currency",
    DateTime: "date_time",
    Image: "image",
    Video: "video",
    Document: "document",
} as const;
export type TemplateParameterType = (typeof TemplateParameterType)[keyof typeof TemplateParameterType];
