// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface TemplateMessage {
    name: string;
    language: WhatsappSDK.TemplateLanguage;
    namespace?: string | undefined;
    components?: WhatsappSDK.TemplateComponent[] | undefined;
}
