// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface TemplateParameter {
    type: WhatsappSDK.TemplateParameterType;
    text?: string | undefined;
    currency?: WhatsappSDK.TemplateCurrency | undefined;
    date_time?: WhatsappSDK.TemplateDateTime | undefined;
    image?: WhatsappSDK.ImageByLink | undefined;
    video?: WhatsappSDK.VideoByLink | undefined;
    document?: WhatsappSDK.DocumentByLink | undefined;
}
