// This file was auto-generated by Fern from our API Definition.

export const TemplateButtonParameterType = {
    Payload: "payload",
    Text: "text",
    CouponCode: "coupon_code",
    Action: "action",
} as const;
export type TemplateButtonParameterType =
    (typeof TemplateButtonParameterType)[keyof typeof TemplateButtonParameterType];
