// This file was auto-generated by Fern from our API Definition.

export const TemplateComponentType = {
    Header: "header",
    Body: "body",
    Footer: "footer",
    Button: "button",
} as const;
export type TemplateComponentType = (typeof TemplateComponentType)[keyof typeof TemplateComponentType];
