// This file was auto-generated by Fern from our API Definition.

export const TemplateButtonSubType = {
    QuickReply: "quick_reply",
    Url: "url",
    CopyCode: "copy_code",
    Catalog: "CATALOG",
} as const;
export type TemplateButtonSubType = (typeof TemplateButtonSubType)[keyof typeof TemplateButtonSubType];
