// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface TemplateHeaderBodyFooterComponent {
    type: WhatsappSDK.TemplateComponentType;
    parameters?: WhatsappSDK.TemplateParameter[] | undefined;
}
