// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface TemplateButtonComponent {
    type: "button";
    sub_type: WhatsappSDK.TemplateButtonSubType;
    index?: unknown | undefined;
    parameters: WhatsappSDK.TemplateButtonParameter[];
}
