// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiTemplateParameter {
    type: WhatsappSDK.WhatsappApiTemplateParameterType;
    text?: string | undefined;
    currency?: WhatsappSDK.WhatsappApiTemplateCurrency | undefined;
    date_time?: WhatsappSDK.WhatsappApiTemplateDateTime | undefined;
    image?: WhatsappSDK.WhatsappApiImageByLink | undefined;
    video?: WhatsappSDK.WhatsappApiVideoByLink | undefined;
    document?: WhatsappSDK.WhatsappApiDocumentByLink | undefined;
}
