// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export type WhatsappApiInteractiveHeader =
    | WhatsappSDK.WhatsappApiInteractiveTextHeader
    | WhatsappSDK.WhatsappApiInteractiveVideoHeader
    | WhatsappSDK.WhatsappApiInteractiveDocumentHeader
    | WhatsappSDK.WhatsappApiInteractiveImageHeader;
