// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiSendMessageResponse {
    messaging_product: "whatsapp";
    contacts: WhatsappSDK.WhatsappApiSendMessageContactResult[];
    messages: WhatsappSDK.WhatsappApiSendMessageMessageResult[];
}
