// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiInteractiveMessage {
    type: WhatsappSDK.WhatsappApiInteractiveActionType;
    body?: WhatsappSDK.WhatsappApiInteractiveBody | undefined;
    footer?: WhatsappSDK.WhatsappApiInteractiveFooter | undefined;
    header?: WhatsappSDK.WhatsappApiInteractiveHeader | undefined;
    action: WhatsappSDK.WhatsappApiInteractiveAction;
}
