// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiTemplateButtonSubType = {
    QuickReply: "quick_reply",
    Url: "url",
    CopyCode: "copy_code",
    Catalog: "CATALOG",
} as const;
export type WhatsappApiTemplateButtonSubType =
    (typeof WhatsappApiTemplateButtonSubType)[keyof typeof WhatsappApiTemplateButtonSubType];
