// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiInteractiveFlowAction = {
    Navigate: "navigate",
    DataExchange: "data_exchange",
} as const;
export type WhatsappApiInteractiveFlowAction =
    (typeof WhatsappApiInteractiveFlowAction)[keyof typeof WhatsappApiInteractiveFlowAction];
