// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiTemplateButtonParameter {
    type: WhatsappSDK.WhatsappApiTemplateButtonParameterType;
    payload?: string | undefined;
    text?: string | undefined;
    coupon_code?: string | undefined;
    action?: WhatsappSDK.WhatsappApiTemplateCatalogAction | undefined;
}
