// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiTemplateButtonComponent {
    type: "button";
    sub_type: WhatsappSDK.WhatsappApiTemplateButtonSubType;
    index?: unknown | undefined;
    parameters: WhatsappSDK.WhatsappApiTemplateButtonParameter[];
}
