// This file was auto-generated by Fern from our API Definition.

export interface WhatsappApiTemplateDateTime {
    fallback_value: string;
    day_of_week?: number | undefined;
    year?: number | undefined;
    month?: number | undefined;
    day_of_month?: number | undefined;
    hour?: number | undefined;
    minute?: number | undefined;
    calendar?: string | undefined;
}
