// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiInteractiveAction {
    name?: string | undefined;
    parameters?: WhatsappSDK.WhatsappApiInteractiveFlowParameters | undefined;
    button?: string | undefined;
    buttons?: WhatsappSDK.WhatsappApiInteractiveActionButtonReply[] | undefined;
    catalog_id?: string | undefined;
    product_retailer_id?: string | undefined;
    sections?: WhatsappSDK.WhatsappApiInteractiveSection[] | undefined;
    mode?: WhatsappSDK.WhatsappApiFlowMode | undefined;
}
