// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiTemplateComponentType = {
    Header: "header",
    Body: "body",
    Footer: "footer",
    Button: "button",
} as const;
export type WhatsappApiTemplateComponentType =
    (typeof WhatsappApiTemplateComponentType)[keyof typeof WhatsappApiTemplateComponentType];
