// This file was auto-generated by Fern from our API Definition.

export interface WhatsappApiDocumentByLink {
    link: string;
    caption?: string | undefined;
    filename?: string | undefined;
}
