// This file was auto-generated by Fern from our API Definition.

export interface WhatsappApiContactName {
    formatted_name: string;
    first_name?: string | undefined;
    last_name?: string | undefined;
    middle_name?: string | undefined;
    prefix?: string | undefined;
    suffix?: string | undefined;
}
