// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiTemplateButtonParameterType = {
    Payload: "payload",
    Text: "text",
    CouponCode: "coupon_code",
    Action: "action",
} as const;
export type WhatsappApiTemplateButtonParameterType =
    (typeof WhatsappApiTemplateButtonParameterType)[keyof typeof WhatsappApiTemplateButtonParameterType];
