// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiMessageType = {
    Text: "text",
    Reaction: "reaction",
    Location: "location",
    Audio: "audio",
    Document: "document",
    Image: "image",
    Video: "video",
    Sticker: "sticker",
    Interactive: "interactive",
    Template: "template",
    Contacts: "contacts",
} as const;
export type WhatsappApiMessageType = (typeof WhatsappApiMessageType)[keyof typeof WhatsappApiMessageType];
