// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiTemplateMessage {
    name: string;
    language: WhatsappSDK.WhatsappApiTemplateLanguage;
    namespace?: string | undefined;
    components?: WhatsappSDK.WhatsappApiTemplateComponent[] | undefined;
}
