// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiInteractiveSection {
    title: string;
    rows: WhatsappSDK.WhatsappApiInteractiveSectionRow[];
    product_items?: WhatsappSDK.WhatsappApiInteractiveProductItem[] | undefined;
}
