// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiSendMessageRequest {
    messaging_product: "whatsapp";
    to: string;
    type: WhatsappSDK.WhatsappApiMessageType;
    preview_url?: boolean | undefined;
    recipient_type?: string | undefined;
    biz_opaque_callback_data?: string | undefined;
    context?: WhatsappSDK.WhatsappApiSendMessageContext | undefined;
    text?: WhatsappSDK.WhatsappApiTextMessage | undefined;
    reaction?: WhatsappSDK.WhatsappApiReactionMessage | undefined;
    location?: WhatsappSDK.WhatsappApiLocationMessage | undefined;
    audio?: WhatsappSDK.WhatsappApiAudioMessage | undefined;
    document?: WhatsappSDK.WhatsappApiDocumentMessage | undefined;
    image?: WhatsappSDK.WhatsappApiImageMessage | undefined;
    video?: WhatsappSDK.WhatsappApiVideoMessage | undefined;
    sticker?: WhatsappSDK.WhatsappApiStickerMessage | undefined;
    interactive?: WhatsappSDK.WhatsappApiInteractiveMessage | undefined;
    template?: WhatsappSDK.WhatsappApiTemplateMessage | undefined;
    contacts?: WhatsappSDK.WhatsappApiContactMessage | undefined;
}
