// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiInteractiveActionType = {
    Button: "button",
    CatalogMessage: "catalog_message",
    List: "list",
    Product: "product",
    ProductList: "product_list",
    Flow: "flow",
} as const;
export type WhatsappApiInteractiveActionType =
    (typeof WhatsappApiInteractiveActionType)[keyof typeof WhatsappApiInteractiveActionType];
