// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiFlowMode = {
    Draft: "draft",
    Published: "published",
} as const;
export type WhatsappApiFlowMode = (typeof WhatsappApiFlowMode)[keyof typeof WhatsappApiFlowMode];
