// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name",
 *         categories: ["SIGN_UP", "SIGN_UP"]
 *     }
 */
export interface CreateFlowRequestWrapper {
    name: string;
    categories: WhatsappSDK.FlowCategory[];
    clone_flow_id?: string;
    endpoint_uri?: string;
    flow_json?: string;
    publish?: boolean;
}
