// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateFlowMetadataRequestWrapper {
    name?: string;
    categories?: WhatsappSDK.WhatsappApiFlowCategory[];
    endpoint_uri?: string;
    application_id?: string;
}
