// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         file: {
 *             "key": "value"
 *         }
 *     }
 */
export interface UpdateFlowJsonRequest {
    file?: unknown;
}
