// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         fields: "preview.invalidate(false)"
 *     }
 */
export interface WhatsappApiGetFlowPreviewRequest {
    fields: "preview.invalidate(false)";
}
