// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WebhookMessageChangeValue {
    messaging_product: "whatsapp";
    metadata: WhatsappSDK.WebhookMetadataObject;
    contacts?: WhatsappSDK.WebhookContactObject[] | undefined;
    errors?: WhatsappSDK.Errors | undefined;
    messages?: WhatsappSDK.WebhookMessageObject[] | undefined;
    statuses?: WhatsappSDK.WebhookMessageStatusObject[] | undefined;
}
