// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WebhookMessageStatusObject {
    id: string;
    biz_opaque_callback_data?: string | undefined;
    conversation?: WhatsappSDK.WebhookConversation | undefined;
    errors?: WhatsappSDK.Errors | undefined;
    pricing?: WhatsappSDK.WebhookPricing | undefined;
    recipient_id: string;
    status: WhatsappSDK.WebhookMessageStatus;
    timestamp: number;
}
