// This file was auto-generated by Fern from our API Definition.

export interface WebhookSystemObject {
    body: string;
    identity?: string | undefined;
    new_wa_id?: string | undefined;
    wa_id?: string | undefined;
    customer?: string | undefined;
}
