// This file was auto-generated by Fern from our API Definition.

export interface WebhookContextObject {
    forwarded?: boolean | undefined;
    frequently_forwarded?: boolean | undefined;
    from?: string | undefined;
    id?: string | undefined;
}
