// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WebhookConversation {
    id: string;
    origin: WhatsappSDK.WebhookConversationOrigin;
    expiration_timestamp?: number | undefined;
}
