// This file was auto-generated by Fern from our API Definition.

export const WebhookConversationType = {
    Authentication: "authentication",
    Service: "service",
    Utility: "utility",
    Marketing: "marketing",
    ReferralConversation: "referral_conversation",
} as const;
export type WebhookConversationType = (typeof WebhookConversationType)[keyof typeof WebhookConversationType];
