// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WebhookInteractiveObject {
    type: WhatsappSDK.WebhookInteractiveType;
    button_reply?: WhatsappSDK.WebhookButtonReply | undefined;
    list_reply?: WhatsappSDK.WebhookListReply | undefined;
    nfm_reply?: WhatsappSDK.WebhookNfmReply | undefined;
}
