// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WebhookOrderObject {
    catalog_id: string;
    text: string;
    product_items: WhatsappSDK.WebhookProductItem[];
}
