// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

/**
 * Payload delivered by Meta to your webhook endpoint for incoming messages and status updates.
 */
export interface WebhookMessageBody {
    object: "whatsapp_business_account";
    entry: WhatsappSDK.WebhookMessageEntry[];
}
