// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WebhookMessageObject {
    id: string;
    from: string;
    timestamp: number;
    type: WhatsappSDK.WebhookMessageType;
    context?: WhatsappSDK.WebhookContextObject | undefined;
    image?: WhatsappSDK.WebhookImageObject | undefined;
    video?: WhatsappSDK.WebhookVideoObject | undefined;
    interactive?: WhatsappSDK.WebhookInteractiveObject | undefined;
    order?: WhatsappSDK.WebhookOrderObject | undefined;
    referral?: WhatsappSDK.WebhookReferralObject | undefined;
    sticker?: WhatsappSDK.WebhookStickerObject | undefined;
    system?: WhatsappSDK.WebhookSystemObject | undefined;
    text?: WhatsappSDK.WebhookTextObject | undefined;
    identity?: WhatsappSDK.WebhookIdentityObject | undefined;
    audio?: WhatsappSDK.WebhookAudioObject | undefined;
    button?: WhatsappSDK.WebhookButtonObject | undefined;
    document?: WhatsappSDK.WebhookDocumentObject | undefined;
    errors?: WhatsappSDK.Errors | undefined;
}
