// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

/**
 * Decrypted contents of a WebhookFlowEncryptedBody.
 */
export interface WebhookFlowDecryptedBody {
    version: string;
    screen: string;
    action: WhatsappSDK.FlowAction;
    data: Record<string, unknown>;
    flow_token: string;
}
