// This file was auto-generated by Fern from our API Definition.

export interface WebhookStickerObject {
    mime_type: string;
    sha256: string;
    id: string;
    animated?: string | undefined;
}
