// This file was auto-generated by Fern from our API Definition.

export const WebhookInteractiveType = {
    ButtonReply: "button_reply",
    ListReply: "list_reply",
    NfmReply: "nfm_reply",
} as const;
export type WebhookInteractiveType = (typeof WebhookInteractiveType)[keyof typeof WebhookInteractiveType];
