// This file was auto-generated by Fern from our API Definition.

export const WebhookMessageStatus = {
    Delivered: "delivered",
    Read: "read",
    Sent: "sent",
} as const;
export type WebhookMessageStatus = (typeof WebhookMessageStatus)[keyof typeof WebhookMessageStatus];
