// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiWebhookMessageStatus = {
    Delivered: "delivered",
    Read: "read",
    Sent: "sent",
} as const;
export type WhatsappApiWebhookMessageStatus =
    (typeof WhatsappApiWebhookMessageStatus)[keyof typeof WhatsappApiWebhookMessageStatus];
