// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

/**
 * Decrypted contents of a WhatsappApiWebhookFlowEncryptedBody.
 */
export interface WhatsappApiWebhookFlowDecryptedBody {
    version: string;
    screen: string;
    action: WhatsappSDK.WhatsappApiFlowAction;
    data: Record<string, unknown>;
    flow_token: string;
}
