// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiWebhookMessageStatusObject {
    id: string;
    biz_opaque_callback_data?: string | undefined;
    conversation?: WhatsappSDK.WhatsappApiWebhookConversation | undefined;
    errors?: WhatsappSDK.WhatsappApiErrors | undefined;
    pricing?: WhatsappSDK.WhatsappApiWebhookPricing | undefined;
    recipient_id: string;
    status: WhatsappSDK.WhatsappApiWebhookMessageStatus;
    timestamp: number;
}
