// This file was auto-generated by Fern from our API Definition.

/**
 * Encrypted payload delivered by Meta to your endpoint when a user interacts with a WhatsApp Flow. Decrypt using the business private key and the provided AES key.
 */
export interface WhatsappApiWebhookFlowEncryptedBody {
    encrypted_aes_key: string;
    encrypted_flow_data: string;
    initial_vector: string;
}
