// This file was auto-generated by Fern from our API Definition.

export interface WhatsappApiWebhookReferralObject {
    source_url: string;
    source_type: string;
    source_id: string;
    headline: string;
    body: string;
    media_type: string;
    image_url?: string | undefined;
    video_url?: string | undefined;
    thumbnail_url?: string | undefined;
    ctwa_clid?: string | undefined;
}
