// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiWebhookInteractiveType = {
    ButtonReply: "button_reply",
    ListReply: "list_reply",
    NfmReply: "nfm_reply",
} as const;
export type WhatsappApiWebhookInteractiveType =
    (typeof WhatsappApiWebhookInteractiveType)[keyof typeof WhatsappApiWebhookInteractiveType];
