// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiWebhookMessageChangeValue {
    messaging_product: "whatsapp";
    metadata: WhatsappSDK.WhatsappApiWebhookMetadataObject;
    contacts?: WhatsappSDK.WhatsappApiWebhookContactObject[] | undefined;
    errors?: WhatsappSDK.WhatsappApiErrors | undefined;
    messages?: WhatsappSDK.WhatsappApiWebhookMessageObject[] | undefined;
    statuses?: WhatsappSDK.WhatsappApiWebhookMessageStatusObject[] | undefined;
}
