// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiWebhookContactObject {
    wa_id: string;
    profile: WhatsappSDK.WhatsappApiWebhookContactProfile;
}
