// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiWebhookMessageObject {
    id: string;
    from: string;
    timestamp: number;
    type: WhatsappSDK.WhatsappApiWebhookMessageType;
    context?: WhatsappSDK.WhatsappApiWebhookContextObject | undefined;
    image?: WhatsappSDK.WhatsappApiWebhookImageObject | undefined;
    video?: WhatsappSDK.WhatsappApiWebhookVideoObject | undefined;
    interactive?: WhatsappSDK.WhatsappApiWebhookInteractiveObject | undefined;
    order?: WhatsappSDK.WhatsappApiWebhookOrderObject | undefined;
    referral?: WhatsappSDK.WhatsappApiWebhookReferralObject | undefined;
    sticker?: WhatsappSDK.WhatsappApiWebhookStickerObject | undefined;
    system?: WhatsappSDK.WhatsappApiWebhookSystemObject | undefined;
    text?: WhatsappSDK.WhatsappApiWebhookTextObject | undefined;
    identity?: WhatsappSDK.WhatsappApiWebhookIdentityObject | undefined;
    audio?: WhatsappSDK.WhatsappApiWebhookAudioObject | undefined;
    button?: WhatsappSDK.WhatsappApiWebhookButtonObject | undefined;
    document?: WhatsappSDK.WhatsappApiWebhookDocumentObject | undefined;
    errors?: WhatsappSDK.WhatsappApiErrors | undefined;
}
