// This file was auto-generated by Fern from our API Definition.

export interface WhatsappApiWebhookDocumentObject {
    caption?: string | undefined;
    filename: string;
    sha256: string;
    mime_type: string;
    id: string;
}
