// This file was auto-generated by Fern from our API Definition.

export interface WhatsappApiWebhookImageObject {
    caption?: string | undefined;
    sha256: string;
    id: string;
    mime_type: string;
}
