// This file was auto-generated by Fern from our API Definition.

export interface WhatsappApiWebhookProductItem {
    product_retailer_id: string;
    quantity: number;
    item_price: string;
    currency: string;
}
