// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiWebhookConversationType = {
    Authentication: "authentication",
    Service: "service",
    Utility: "utility",
    Marketing: "marketing",
    ReferralConversation: "referral_conversation",
} as const;
export type WhatsappApiWebhookConversationType =
    (typeof WhatsappApiWebhookConversationType)[keyof typeof WhatsappApiWebhookConversationType];
