// This file was auto-generated by Fern from our API Definition.

export interface WhatsappApiWebhookVideoObject {
    id: string;
    caption?: string | undefined;
    filename?: string | undefined;
    sha256: string;
    mime_type: string;
}
