// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiWebhookInteractiveObject {
    type: WhatsappSDK.WhatsappApiWebhookInteractiveType;
    button_reply?: WhatsappSDK.WhatsappApiWebhookButtonReply | undefined;
    list_reply?: WhatsappSDK.WhatsappApiWebhookListReply | undefined;
    nfm_reply?: WhatsappSDK.WhatsappApiWebhookNfmReply | undefined;
}
