// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiWebhookConversation {
    id: string;
    origin: WhatsappSDK.WhatsappApiWebhookConversationOrigin;
    expiration_timestamp?: number | undefined;
}
