// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiWebhookMessageType = {
    Audio: "audio",
    Button: "button",
    Document: "document",
    Text: "text",
    Image: "image",
    Interactive: "interactive",
    Order: "order",
    Sticker: "sticker",
    System: "system",
    Unknown: "unknown",
    Video: "video",
} as const;
export type WhatsappApiWebhookMessageType =
    (typeof WhatsappApiWebhookMessageType)[keyof typeof WhatsappApiWebhookMessageType];
