// This file was auto-generated by Fern from our API Definition.

export const FlowAction = {
    Init: "INIT",
    Back: "BACK",
    DataExchange: "data_exchange",
    Navigate: "navigate",
    Ping: "ping",
} as const;
export type FlowAction = (typeof FlowAction)[keyof typeof FlowAction];
