// This file was auto-generated by Fern from our API Definition.

export const FlowStatus = {
    Draft: "DRAFT",
    Published: "PUBLISHED",
    Deprecated: "DEPRECATED",
    Blocked: "BLOCKED",
    Throttled: "THROTTLED",
} as const;
export type FlowStatus = (typeof FlowStatus)[keyof typeof FlowStatus];
