// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

/**
 * Summary row returned in list responses.
 */
export interface FlowSummary {
    id: string;
    name: string;
    status: WhatsappSDK.FlowStatus;
    categories: WhatsappSDK.FlowCategory[];
    validation_errors: WhatsappSDK.FlowValidationError[];
}
