// This file was auto-generated by Fern from our API Definition.

export const FlowCanSendMessageStatus = {
    Available: "AVAILABLE",
    Limited: "LIMITED",
    Blocked: "BLOCKED",
} as const;
export type FlowCanSendMessageStatus = (typeof FlowCanSendMessageStatus)[keyof typeof FlowCanSendMessageStatus];
