// This file was auto-generated by Fern from our API Definition.

export const FlowCategory = {
    SignUp: "SIGN_UP",
    SignIn: "SIGN_IN",
    AppointmentBooking: "APPOINTMENT_BOOKING",
    LeadGeneration: "LEAD_GENERATION",
    ContactUs: "CONTACT_US",
    CustomerSupport: "CUSTOMER_SUPPORT",
    Survey: "SURVEY",
    Other: "OTHER",
} as const;
export type FlowCategory = (typeof FlowCategory)[keyof typeof FlowCategory];
