// This file was auto-generated by Fern from our API Definition.

export interface FlowMediaEncryptionMetadata {
    encrypted_hash: string;
    iv: string;
    encryption_key: string;
    hmac_key: string;
    plaintext_hash: string;
}
