// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiFlowAction = {
    Init: "INIT",
    Back: "BACK",
    DataExchange: "data_exchange",
    Navigate: "navigate",
    Ping: "ping",
} as const;
export type WhatsappApiFlowAction = (typeof WhatsappApiFlowAction)[keyof typeof WhatsappApiFlowAction];
