// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiFlowMetadata {
    name: string;
    categories: WhatsappSDK.WhatsappApiFlowCategory[];
    application_id?: string | undefined;
    endpoint_uri?: string | undefined;
}
