// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiFlowStatus = {
    Draft: "DRAFT",
    Published: "PUBLISHED",
    Deprecated: "DEPRECATED",
    Blocked: "BLOCKED",
    Throttled: "THROTTLED",
} as const;
export type WhatsappApiFlowStatus = (typeof WhatsappApiFlowStatus)[keyof typeof WhatsappApiFlowStatus];
