// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiFlowMedia {
    media_id: string;
    cdn_url: string;
    file_name: string;
    encryption_metadata: WhatsappSDK.WhatsappApiFlowMediaEncryptionMetadata;
}
