// This file was auto-generated by Fern from our API Definition.

export const WhatsappApiFlowCanSendMessageStatus = {
    Available: "AVAILABLE",
    Limited: "LIMITED",
    Blocked: "BLOCKED",
} as const;
export type WhatsappApiFlowCanSendMessageStatus =
    (typeof WhatsappApiFlowCanSendMessageStatus)[keyof typeof WhatsappApiFlowCanSendMessageStatus];
