// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

/**
 * Full flow detail returned by a single-flow read.
 */
export interface WhatsappApiFlowDetail extends WhatsappSDK.WhatsappApiFlowSummary {
    json_version?: string | undefined;
    data_api_version?: string | undefined;
    endpoint_uri?: string | undefined;
    preview?: WhatsappSDK.WhatsappApiFlowPreviewResponse | undefined;
    health_status?: WhatsappSDK.WhatsappApiFlowHealthStatus | undefined;
}
