// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

/**
 * Summary row returned in list responses.
 */
export interface WhatsappApiFlowSummary {
    id: string;
    name: string;
    status: WhatsappSDK.WhatsappApiFlowStatus;
    categories: WhatsappSDK.WhatsappApiFlowCategory[];
    validation_errors: WhatsappSDK.WhatsappApiFlowValidationError[];
}
