// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiCreateFlowRequest {
    name: string;
    categories: WhatsappSDK.WhatsappApiFlowCategory[];
    clone_flow_id?: string | undefined;
    endpoint_uri?: string | undefined;
    flow_json?: string | undefined;
    publish?: boolean | undefined;
}
