// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiFlowPreviewParams {
    interactive?: boolean | undefined;
    flow_token?: string | undefined;
    flow_action?: WhatsappSDK.WhatsappApiInteractiveFlowAction | undefined;
    flow_action_payload?: WhatsappSDK.WhatsappApiFlowActionPayload | undefined;
    phone_number?: string | undefined;
    debug?: boolean | undefined;
}
