// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiUpdateFlowMetadataRequest {
    name?: string | undefined;
    categories?: WhatsappSDK.WhatsappApiFlowCategory[] | undefined;
    endpoint_uri?: string | undefined;
    application_id?: string | undefined;
}
