// This file was auto-generated by Fern from our API Definition.

import type * as WhatsappSDK from "../../../index.js";

export interface WhatsappApiRegisterNumberRequest {
    messaging_product: "whatsapp";
    pin: string;
    data_localization_region?: WhatsappSDK.WhatsappApiIsoCountryCode | undefined;
}
