// This file was auto-generated by Fern from our API Definition.

import { WhatsappSDKClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("FlowsClient", () => {
    test("createFlow", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });
        const rawRequestBody = { name: "name", categories: ["SIGN_UP", "SIGN_UP"] };
        const rawResponseBody = { id: "id" };

        server
            .mockEndpoint()
            .post("/wabaId/flows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.createFlow("wabaId", {
            name: "name",
            categories: ["SIGN_UP", "SIGN_UP"],
        });
        expect(response).toEqual({
            id: "id",
        });
    });

    test("updateFlowMetadata", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .post("/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.updateFlowMetadata("flowId");
        expect(response).toEqual({
            success: true,
        });
    });

    test("listFlows", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    name: "name",
                    status: "DRAFT",
                    categories: ["SIGN_UP", "SIGN_UP"],
                    validation_errors: [
                        {
                            error: "error",
                            error_type: "error_type",
                            message: "message",
                            line_start: 1,
                            line_end: 1,
                            column_start: 1,
                            column_end: 1,
                        },
                        {
                            error: "error",
                            error_type: "error_type",
                            message: "message",
                            line_start: 1,
                            line_end: 1,
                            column_start: 1,
                            column_end: 1,
                        },
                    ],
                },
                {
                    id: "id",
                    name: "name",
                    status: "DRAFT",
                    categories: ["SIGN_UP", "SIGN_UP"],
                    validation_errors: [
                        {
                            error: "error",
                            error_type: "error_type",
                            message: "message",
                            line_start: 1,
                            line_end: 1,
                            column_start: 1,
                            column_end: 1,
                        },
                        {
                            error: "error",
                            error_type: "error_type",
                            message: "message",
                            line_start: 1,
                            line_end: 1,
                            column_start: 1,
                            column_end: 1,
                        },
                    ],
                },
            ],
            paging: { cursors: { before: "before", after: "after" } },
        };

        server.mockEndpoint().get("/wabaId/flows").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.flows.listFlows("wabaId");
        expect(response).toEqual({
            data: [
                {
                    id: "id",
                    name: "name",
                    status: "DRAFT",
                    categories: ["SIGN_UP", "SIGN_UP"],
                    validation_errors: [
                        {
                            error: "error",
                            error_type: "error_type",
                            message: "message",
                            line_start: 1,
                            line_end: 1,
                            column_start: 1,
                            column_end: 1,
                        },
                        {
                            error: "error",
                            error_type: "error_type",
                            message: "message",
                            line_start: 1,
                            line_end: 1,
                            column_start: 1,
                            column_end: 1,
                        },
                    ],
                },
                {
                    id: "id",
                    name: "name",
                    status: "DRAFT",
                    categories: ["SIGN_UP", "SIGN_UP"],
                    validation_errors: [
                        {
                            error: "error",
                            error_type: "error_type",
                            message: "message",
                            line_start: 1,
                            line_end: 1,
                            column_start: 1,
                            column_end: 1,
                        },
                        {
                            error: "error",
                            error_type: "error_type",
                            message: "message",
                            line_start: 1,
                            line_end: 1,
                            column_start: 1,
                            column_end: 1,
                        },
                    ],
                },
            ],
            paging: {
                cursors: {
                    before: "before",
                    after: "after",
                },
            },
        });
    });

    test("getFlow", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });

        const rawResponseBody = {
            json_version: "json_version",
            data_api_version: "data_api_version",
            endpoint_uri: "endpoint_uri",
            preview: { id: "id", preview: { preview_url: "preview_url", expires_at: "expires_at" } },
            health_status: { can_send_message: "AVAILABLE" },
            id: "id",
            name: "name",
            status: "DRAFT",
            categories: ["SIGN_UP", "SIGN_UP"],
            validation_errors: [
                {
                    error: "error",
                    error_type: "error_type",
                    message: "message",
                    line_start: 1,
                    line_end: 1,
                    column_start: 1,
                    column_end: 1,
                },
                {
                    error: "error",
                    error_type: "error_type",
                    message: "message",
                    line_start: 1,
                    line_end: 1,
                    column_start: 1,
                    column_end: 1,
                },
            ],
        };

        server.mockEndpoint().get("/flowId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.flows.getFlow("flowId");
        expect(response).toEqual({
            json_version: "json_version",
            data_api_version: "data_api_version",
            endpoint_uri: "endpoint_uri",
            preview: {
                id: "id",
                preview: {
                    preview_url: "preview_url",
                    expires_at: "expires_at",
                },
            },
            health_status: {
                can_send_message: "AVAILABLE",
            },
            id: "id",
            name: "name",
            status: "DRAFT",
            categories: ["SIGN_UP", "SIGN_UP"],
            validation_errors: [
                {
                    error: "error",
                    error_type: "error_type",
                    message: "message",
                    line_start: 1,
                    line_end: 1,
                    column_start: 1,
                    column_end: 1,
                },
                {
                    error: "error",
                    error_type: "error_type",
                    message: "message",
                    line_start: 1,
                    line_end: 1,
                    column_start: 1,
                    column_end: 1,
                },
            ],
        });
    });

    test("deleteFlow", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });

        const rawResponseBody = { success: true };

        server.mockEndpoint().delete("/flowId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.flows.deleteFlow("flowId");
        expect(response).toEqual({
            success: true,
        });
    });

    test("updateFlowJson", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });
        const rawRequestBody = { name: "flow.json", asset_type: "FLOW_JSON", file: { key: "value" } };
        const rawResponseBody = {
            success: true,
            validation_errors: [
                {
                    error: "error",
                    error_type: "error_type",
                    message: "message",
                    line_start: 1,
                    line_end: 1,
                    column_start: 1,
                    column_end: 1,
                },
                {
                    error: "error",
                    error_type: "error_type",
                    message: "message",
                    line_start: 1,
                    line_end: 1,
                    column_start: 1,
                    column_end: 1,
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/flowId/assets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.updateFlowJson("flowId", {
            file: {
                key: "value",
            },
        });
        expect(response).toEqual({
            success: true,
            validation_errors: [
                {
                    error: "error",
                    error_type: "error_type",
                    message: "message",
                    line_start: 1,
                    line_end: 1,
                    column_start: 1,
                    column_end: 1,
                },
                {
                    error: "error",
                    error_type: "error_type",
                    message: "message",
                    line_start: 1,
                    line_end: 1,
                    column_start: 1,
                    column_end: 1,
                },
            ],
        });
    });

    test("getFlowPreview", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });

        const rawResponseBody = { id: "id", preview: { preview_url: "preview_url", expires_at: "expires_at" } };

        server.mockEndpoint().get("/flowId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.flows.getFlowPreview("flowId", {
            fields: "preview.invalidate(false)",
        });
        expect(response).toEqual({
            id: "id",
            preview: {
                preview_url: "preview_url",
                expires_at: "expires_at",
            },
        });
    });

    test("publishFlow", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });

        const rawResponseBody = { success: true };

        server.mockEndpoint().post("/flowId/publish").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.flows.publishFlow("flowId");
        expect(response).toEqual({
            success: true,
        });
    });
});
