// This file was auto-generated by Fern from our API Definition.

import { WhatsappSDKClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MediaClient", () => {
    test("getMedia", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });

        const rawResponseBody = {
            messaging_product: "whatsapp",
            url: "url",
            mime_type: "mime_type",
            sha256: "sha256",
            file_size: 1,
            id: "id",
        };

        server.mockEndpoint().get("/mediaId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.media.getMedia("mediaId");
        expect(response).toEqual({
            messaging_product: "whatsapp",
            url: "url",
            mime_type: "mime_type",
            sha256: "sha256",
            file_size: 1,
            id: "id",
        });
    });
});
