// This file was auto-generated by Fern from our API Definition.

import { WhatsappSDKClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MessagesClient", () => {
    test("sendMessage", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });
        const rawRequestBody = { messaging_product: "whatsapp", to: "to", type: "text" };
        const rawResponseBody = {
            messaging_product: "whatsapp",
            contacts: [
                { wa_id: "wa_id", profile: { name: "name" } },
                { wa_id: "wa_id", profile: { name: "name" } },
            ],
            messages: [{ id: "id" }, { id: "id" }],
        };

        server
            .mockEndpoint()
            .post("/numberId/messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.messages.sendMessage("numberId", {
            messaging_product: "whatsapp",
            to: "to",
            type: "text",
        });
        expect(response).toEqual({
            messaging_product: "whatsapp",
            contacts: [
                {
                    wa_id: "wa_id",
                    profile: {
                        name: "name",
                    },
                },
                {
                    wa_id: "wa_id",
                    profile: {
                        name: "name",
                    },
                },
            ],
            messages: [
                {
                    id: "id",
                },
                {
                    id: "id",
                },
            ],
        });
    });

    test("showTypingIndicator", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });
        const rawRequestBody = {
            messaging_product: "whatsapp",
            status: "read",
            message_id: "message_id",
            typing_indicator: { type: "text" },
        };
        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .post("/numberId/messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.messages.showTypingIndicator("numberId", {
            messaging_product: "whatsapp",
            status: "read",
            message_id: "message_id",
            typing_indicator: {
                type: "text",
            },
        });
        expect(response).toEqual({
            success: true,
        });
    });
});
