// This file was auto-generated by Fern from our API Definition.

import { WhatsappSDKClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WabaClient", () => {
    test("uploadEncryptionKey", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });
        const rawRequestBody = { business_public_key: "business_public_key" };

        server
            .mockEndpoint()
            .post("/numberId/whatsapp_business_encryption")
            .formUrlEncodedBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.waba.uploadEncryptionKey("numberId", {
            business_public_key: "business_public_key",
        });
        expect(response).toEqual(undefined);
    });

    test("registerNumber", async () => {
        const server = mockServerPool.createServer();
        const client = new WhatsappSDKClient({
            maxRetries: 0,
            accessToken: "test",
            environment: { graph: server.baseUrl },
        });
        const rawRequestBody = { messaging_product: "whatsapp", pin: "pin" };

        server.mockEndpoint().post("/numberId/register").jsonBody(rawRequestBody).respondWith().statusCode(200).build();

        const response = await client.waba.registerNumber("numberId", {
            messaging_product: "whatsapp",
            pin: "pin",
        });
        expect(response).toEqual(undefined);
    });
});
