// This file was auto-generated by Fern from our API Definition.

import { FlowsClient } from "./api/resources/flows/client/Client.js";
import { MediaClient } from "./api/resources/media/client/Client.js";
import { MessagesClient } from "./api/resources/messages/client/Client.js";
import { WabaClient } from "./api/resources/waba/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";
import * as environments from "./environments.js";

export declare namespace WhatsappSDKClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class WhatsappSDKClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<WhatsappSDKClient.Options>;
    protected _flows: FlowsClient | undefined;
    protected _media: MediaClient | undefined;
    protected _messages: MessagesClient | undefined;
    protected _waba: WabaClient | undefined;

    constructor(options: WhatsappSDKClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get flows(): FlowsClient {
        return (this._flows ??= new FlowsClient(this._options));
    }

    public get media(): MediaClient {
        return (this._media ??= new MediaClient(this._options));
    }

    public get messages(): MessagesClient {
        return (this._messages ??= new MessagesClient(this._options));
    }

    public get waba(): WabaClient {
        return (this._waba ??= new WabaClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl:
                    this._options.baseUrl ??
                    (async () => {
                        const env = await core.Supplier.get(this._options.environment);
                        return typeof env === "string"
                            ? env
                            : ((env as Record<string, string>)?.graph ??
                                  environments.WhatsappSDKEnvironment.Production.graph);
                    }),
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
