// This file was auto-generated by Fern from our API Definition.

export interface WhatsappSDKEnvironmentUrls {
    graph: string;
}

export const WhatsappSDKEnvironment = {
    Production: {
        graph: "https://graph.facebook.com",
    },
} as const;

export type WhatsappSDKEnvironment = typeof WhatsappSDKEnvironment.Production;
